import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.locator('input[name="txtUser"]').click();
  await page.locator('input[name="txtUser"]').fill('_testUser6');
  await page.locator('input[name="txtPwd"]').click();
  await page.locator('input[name="txtPwd"]').fill('123456');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: 'Account' }).click();
  await page.getByRole('link', { name: 'My Account' }).click();
  await page.getByRole('button', { name: 'Edit Account' }).click();
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').fill('a@b');
  await page.getByRole('button', { name: 'Update Account' }).click();
  await page.getByText('- An invalid email was').click();
  await expect(page.locator('form')).toContainText('- An invalid email was provided');
  await page.getByLabel('Email:').click();
  await page.getByLabel('Email:').press('ArrowLeft');
  await page.getByLabel('Email:').press('ArrowLeft');
  await page.getByLabel('Email:').press('ArrowLeft');
  await page.getByLabel('Email:').press('ArrowRight');
  await page.getByLabel('Email:').press('ArrowRight');
  await page.getByLabel('Email:').press('ArrowRight');
  await page.getByLabel('Email:').press('ArrowRight');
  await page.getByLabel('Email:').press('ArrowRight');
  await page.getByLabel('Email:').fill('testuser62@gmail.com');
  await page.getByRole('button', { name: 'Update Account' }).click();
  await page.getByText('Email: testuser62@gmail.com').click();
  await expect(page.locator('body')).toContainText('Email: testuser62@gmail.com');
  await page.getByRole('button', { name: 'Edit Account' }).click();
  await page.getByLabel('New Password:', { exact: true }).click();
  await page.getByLabel('New Password:', { exact: true }).fill('123');
  await page.getByLabel('Confirm New Password:').click();
  await page.getByLabel('Confirm New Password:').fill('12');
  await page.getByRole('button', { name: 'Update Account' }).click();
  await page.getByText('- Password should be longer').click();
  await expect(page.locator('form')).toContainText('- Password should be longer than 5 characters - The passwords given are different');
  await page.getByLabel('New Password:', { exact: true }).click();
  await page.getByLabel('New Password:', { exact: true }).fill('1234567');
  await page.getByLabel('Confirm New Password:').click();
  await page.getByLabel('Confirm New Password:').fill('1234567');
  await page.getByRole('button', { name: 'Update Account' }).click();
  await page.getByRole('button', { name: 'Account', exact: true }).click();
  await page.getByRole('link', { name: 'Log Out' }).click();
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.locator('input[name="txtUser"]').click();
  await page.locator('input[name="txtUser"]').fill('_testUser6');
  await page.locator('input[name="txtPwd"]').click();
  await page.locator('input[name="txtPwd"]').fill('1234567');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.locator('div').filter({ hasText: /^_testUser6$/ }).click();
  await expect(page.locator('body')).toContainText('_testUser6');
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'Account', exact: true }).click();
  await page.getByRole('link', { name: 'My Account' }).click();
  await page.getByRole('button', { name: 'Edit Account' }).click();
  await page.getByLabel('New Password:', { exact: true }).click();
  await page.getByLabel('New Password:', { exact: true }).fill('123456');
  await page.getByLabel('Confirm New Password:').click();
  await page.getByLabel('Confirm New Password:').fill('123456');
  await page.getByRole('button', { name: 'Update Account' }).click();
  await page.getByRole('button', { name: 'Account', exact: true }).click();
  await page.getByRole('link', { name: 'Log Out' }).click();
});