import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.locator('input[name="txtUser"]').click();
  await page.locator('input[name="txtUser"]').fill('_testUser8');
  await page.locator('input[name="txtPwd"]').click();
  await page.locator('input[name="txtPwd"]').fill('123456');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Shop' }).click();
  await page.getByPlaceholder('Search products...').click();
  await page.getByPlaceholder('Search products...').fill('5');
  await page.locator('select[name="orderBy"]').selectOption('price');
  await page.locator('select[name="pageSize"]').selectOption('2');
  await page.getByRole('button', { name: 'Search and Sort Products' }).click();
  await page.locator('select[name="direction"]').selectOption('ASC');
  await page.locator('select[name="direction"]').selectOption('DESC');
  await page.getByRole('button', { name: 'Search and Sort Products' }).click();
  await page.locator('#quantity_5').click();
  await page.locator('#quantity_5').fill('7');
  // await page.locator('#quantity_5').press('Enter');
  // await page.goto('http://localhost:3000/shop?searchTerm=5&orderBy=price&direction=DESC&pageSize=2');
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('button', { name: 'Remove from Cart' }).click();
  await page.getByRole('button', { name: 'Remove from Cart' }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('link', { name: 'Cart' }).click();
  await page.getByText('Quantity:').click();
  await expect(page.locator('body')).toContainText('Quantity: 7');
  await page.getByRole('button', { name: 'Remove' }).click();
  await expect(page.getByRole('paragraph')).toContainText('Your cart is empty.');
  await page.getByRole('link', { name: 'Shop' }).click();
  await page.getByText('Price: Free').click();
  await page.locator('#product_5').getByText('Unlimited quantity').click();
  await page.locator('#quantity_5').click();
  await page.locator('#quantity_5').fill('9');
  await page.locator('#product_5').getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('link', { name: 'Cart' }).click();
  await page.getByText('Total Cost: $').click();
  await expect(page.locator('body')).toContainText('Total Cost: $0.00');
  await page.getByRole('button', { name: 'Checkout' }).click();
});